/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alexa
 */
public class frmElegirPerfil extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmElegirPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnEditarPerfiles = new javax.swing.JButton();
        panPerfiles = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        lblP1 = new javax.swing.JLabel();
        btnP1 = new javax.swing.JButton();
        btnCrearPerfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        btnCrearPerfil1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnP1_2 = new javax.swing.JButton();
        lblP1_2 = new javax.swing.JLabel();
        btnP2 = new javax.swing.JButton();
        lblP2 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        btnCrearPerfil2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnP1_3 = new javax.swing.JButton();
        lblP1_3 = new javax.swing.JLabel();
        btnP2_1 = new javax.swing.JButton();
        lblP2_1 = new javax.swing.JLabel();
        btnP3 = new javax.swing.JButton();
        lblP3 = new javax.swing.JLabel();
        P4 = new javax.swing.JPanel();
        btnCrearPerfil3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnP1_4 = new javax.swing.JButton();
        lblP1_4 = new javax.swing.JLabel();
        btnP2_2 = new javax.swing.JButton();
        lblP2_2 = new javax.swing.JLabel();
        btnP3_1 = new javax.swing.JButton();
        lblP3_1 = new javax.swing.JLabel();
        btnP4 = new javax.swing.JButton();
        lblP4 = new javax.swing.JLabel();
        P5 = new javax.swing.JPanel();
        btnCrearPerfil4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnP1_5 = new javax.swing.JButton();
        lblP1_5 = new javax.swing.JLabel();
        btnP2_3 = new javax.swing.JButton();
        lblP2_3 = new javax.swing.JLabel();
        btnP3_2 = new javax.swing.JButton();
        lblP3_2 = new javax.swing.JLabel();
        btnP4_1 = new javax.swing.JButton();
        lblP4_1 = new javax.swing.JLabel();
        btnP5 = new javax.swing.JButton();
        lblP5 = new javax.swing.JLabel();
        P6 = new javax.swing.JPanel();
        btnCrearPerfil5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnP1_6 = new javax.swing.JButton();
        lblP1_6 = new javax.swing.JLabel();
        btnP2_4 = new javax.swing.JButton();
        lblP2_4 = new javax.swing.JLabel();
        btnP3_3 = new javax.swing.JButton();
        lblP3_3 = new javax.swing.JLabel();
        btnP4_2 = new javax.swing.JButton();
        lblP4_2 = new javax.swing.JLabel();
        btnP5_1 = new javax.swing.JButton();
        lblP5_1 = new javax.swing.JLabel();
        btnP6 = new javax.swing.JButton();
        lblP6 = new javax.swing.JLabel();
        P7 = new javax.swing.JPanel();
        btnP1_7 = new javax.swing.JButton();
        lblP1_7 = new javax.swing.JLabel();
        btnP2_5 = new javax.swing.JButton();
        lblP2_5 = new javax.swing.JLabel();
        btnP3_4 = new javax.swing.JButton();
        lblP3_4 = new javax.swing.JLabel();
        btnP4_3 = new javax.swing.JButton();
        lblP4_3 = new javax.swing.JLabel();
        btnP5_2 = new javax.swing.JButton();
        lblP5_2 = new javax.swing.JLabel();
        btnP6_1 = new javax.swing.JButton();
        lblP6_1 = new javax.swing.JLabel();
        btnP7 = new javax.swing.JButton();
        lblP7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panPrincipal.setBackground(new java.awt.Color(26, 29, 41));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1280, 205));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1280, 205));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1280, 205));
        panPrincipal.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 249, 249));
        jLabel1.setText("¿Quién eres?");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/80px-Disney_logo.png"))); // NOI18N

        btnEditarPerfiles.setBackground(new java.awt.Color(153, 153, 153));
        btnEditarPerfiles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEditarPerfiles.setForeground(new java.awt.Color(249, 249, 249));
        btnEditarPerfiles.setText("EDITAR PERFILES");
        btnEditarPerfiles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(jLabel1)
                .addContainerGap(626, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panPrincipal, java.awt.BorderLayout.PAGE_START);

        panPerfiles.setBackground(new java.awt.Color(255, 255, 255));
        panPerfiles.setForeground(new java.awt.Color(255, 255, 255));
        panPerfiles.setLayout(new java.awt.CardLayout());

        P1.setBackground(new java.awt.Color(26, 29, 41));

        lblP1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1.setForeground(new java.awt.Color(249, 249, 249));
        lblP1.setText("Perfil 1");

        btnP1.setBorder(null);

        btnCrearPerfil.setBackground(new java.awt.Color(26, 29, 41));
        btnCrearPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPerfiles.png"))); // NOI18N
        btnCrearPerfil.setBorder(null);
        btnCrearPerfil.setBorderPainted(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 249, 249));
        jLabel3.setText("Crear perfil");

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                        .addComponent(lblP1)
                        .addGap(316, 316, 316)
                        .addComponent(jLabel3)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                        .addComponent(btnP1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258)
                        .addComponent(btnCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnP1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblP1))
                .addGap(215, 215, 215))
        );

        panPerfiles.add(P1, "card3");

        P2.setBackground(new java.awt.Color(26, 29, 41));

        btnCrearPerfil1.setBackground(new java.awt.Color(26, 29, 41));
        btnCrearPerfil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPerfiles.png"))); // NOI18N
        btnCrearPerfil1.setBorder(null);
        btnCrearPerfil1.setBorderPainted(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 249, 249));
        jLabel5.setText("Crear perfil");

        btnP1_2.setBorder(null);

        lblP1_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_2.setText("Perfil 1");

        btnP2.setBorder(null);

        lblP2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2.setForeground(new java.awt.Color(249, 249, 249));
        lblP2.setText("Perfil 2");

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(lblP1_2)
                        .addGap(140, 140, 140)
                        .addComponent(lblP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnP1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)))
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)))
                .addGap(315, 315, 315))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P2Layout.createSequentialGroup()
                        .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)))
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP2)
                    .addComponent(lblP1_2)
                    .addComponent(jLabel5))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panPerfiles.add(P2, "card2");

        P3.setBackground(new java.awt.Color(26, 29, 41));

        btnCrearPerfil2.setBackground(new java.awt.Color(26, 29, 41));
        btnCrearPerfil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPerfiles.png"))); // NOI18N
        btnCrearPerfil2.setBorder(null);
        btnCrearPerfil2.setBorderPainted(false);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 249, 249));
        jLabel6.setText("Crear perfil");

        btnP1_3.setBorder(null);

        lblP1_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_3.setText("Perfil 1");

        btnP2_1.setBorder(null);

        lblP2_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_1.setText("Perfil 2");

        btnP3.setBorder(null);

        lblP3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3.setForeground(new java.awt.Color(249, 249, 249));
        lblP3.setText("Perfil 3");

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(lblP1_3)
                        .addGap(146, 146, 146)
                        .addComponent(lblP2_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(btnP1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnP2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(lblP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(357, 357, 357))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P3Layout.createSequentialGroup()
                        .addComponent(btnCrearPerfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315))))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(btnCrearPerfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6))
                    .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(P3Layout.createSequentialGroup()
                            .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(lblP3))
                        .addGroup(P3Layout.createSequentialGroup()
                            .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnP2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnP1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblP2_1)
                                .addGroup(P3Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblP1_3))))))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panPerfiles.add(P3, "card4");

        P4.setBackground(new java.awt.Color(26, 29, 41));

        btnCrearPerfil3.setBackground(new java.awt.Color(26, 29, 41));
        btnCrearPerfil3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPerfiles.png"))); // NOI18N
        btnCrearPerfil3.setBorder(null);
        btnCrearPerfil3.setBorderPainted(false);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 249, 249));
        jLabel7.setText("Crear perfil");

        btnP1_4.setBorder(null);

        lblP1_4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_4.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_4.setText("Perfil 1");

        btnP2_2.setBorder(null);

        lblP2_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_2.setText("Perfil 2");

        btnP3_1.setBorder(null);

        lblP3_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_1.setText("Perfil 3");

        btnP4.setBorder(null);

        lblP4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4.setForeground(new java.awt.Color(249, 249, 249));
        lblP4.setText("Perfil 4");

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(lblP1_4)
                        .addGap(146, 146, 146)
                        .addComponent(lblP2_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(btnP1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnP2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(lblP3_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnP4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblP4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPerfil3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)))
                .addGap(180, 180, 180))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(P4Layout.createSequentialGroup()
                            .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnP3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnP4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblP3_1)
                                .addComponent(lblP4)))
                        .addGroup(P4Layout.createSequentialGroup()
                            .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnP2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnP1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblP2_2)
                                .addGroup(P4Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblP1_4)))))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(btnCrearPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panPerfiles.add(P4, "card4");

        P5.setBackground(new java.awt.Color(26, 29, 41));

        btnCrearPerfil4.setBackground(new java.awt.Color(26, 29, 41));
        btnCrearPerfil4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPerfiles.png"))); // NOI18N
        btnCrearPerfil4.setBorder(null);
        btnCrearPerfil4.setBorderPainted(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 249, 249));
        jLabel8.setText("Crear perfil");

        btnP1_5.setBorder(null);

        lblP1_5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_5.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_5.setText("Perfil 1");

        btnP2_3.setBorder(null);

        lblP2_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_3.setText("Perfil 2");

        btnP3_2.setBorder(null);

        lblP3_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_2.setText("Perfil 3");

        btnP4_1.setBorder(null);

        lblP4_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP4_1.setText("Perfil 4");

        btnP5.setBorder(null);

        lblP5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP5.setForeground(new java.awt.Color(249, 249, 249));
        lblP5.setText("Perfil 5");

        javax.swing.GroupLayout P5Layout = new javax.swing.GroupLayout(P5);
        P5.setLayout(P5Layout);
        P5Layout.setHorizontalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P5Layout.createSequentialGroup()
                        .addComponent(lblP1_5)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P5Layout.createSequentialGroup()
                        .addComponent(btnP1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addComponent(lblP2_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addComponent(lblP3_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP4_1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP5)))
                .addGap(91, 91, 91)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42))
                    .addComponent(btnCrearPerfil4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        P5Layout.setVerticalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(P5Layout.createSequentialGroup()
                            .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnP2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnP1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblP2_3)
                                .addGroup(P5Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblP1_5))))
                        .addGroup(P5Layout.createSequentialGroup()
                            .addComponent(btnP3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(lblP3_2))
                        .addComponent(btnP4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnP5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(P5Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblP4_1)
                                .addComponent(lblP5))))
                    .addGroup(P5Layout.createSequentialGroup()
                        .addComponent(btnCrearPerfil4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panPerfiles.add(P5, "card4");

        P6.setBackground(new java.awt.Color(26, 29, 41));

        btnCrearPerfil5.setBackground(new java.awt.Color(26, 29, 41));
        btnCrearPerfil5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearPerfiles.png"))); // NOI18N
        btnCrearPerfil5.setBorder(null);
        btnCrearPerfil5.setBorderPainted(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 249, 249));
        jLabel9.setText("Crear perfil");

        btnP1_6.setBorder(null);

        lblP1_6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_6.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_6.setText("Perfil 1");

        btnP2_4.setBorder(null);

        lblP2_4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_4.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_4.setText("Perfil 2");

        btnP3_3.setBorder(null);

        lblP3_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_3.setText("Perfil 3");

        btnP4_2.setBorder(null);

        lblP4_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP4_2.setText("Perfil 4");

        btnP5_1.setBorder(null);

        lblP5_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP5_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP5_1.setText("Perfil 5");

        btnP6.setBorder(null);

        lblP6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP6.setForeground(new java.awt.Color(249, 249, 249));
        lblP6.setText("Perfil 6");

        javax.swing.GroupLayout P6Layout = new javax.swing.GroupLayout(P6);
        P6.setLayout(P6Layout);
        P6Layout.setHorizontalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P6Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                        .addComponent(lblP1_6)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                        .addComponent(btnP1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addComponent(lblP2_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addComponent(lblP3_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP4_2)))
                .addGap(81, 81, 81)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP5_1)))
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP6)))
                .addGap(178, 178, 178)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40))
                    .addComponent(btnCrearPerfil5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(422, 422, 422))
        );
        P6Layout.setVerticalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P6Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_4)
                            .addGroup(P6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_6))))
                    .addGroup(P6Layout.createSequentialGroup()
                        .addComponent(btnP3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblP3_3))
                    .addComponent(btnP4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP4_2)
                            .addComponent(lblP5_1))))
                .addGap(33, 33, 33)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addComponent(btnCrearPerfil5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnP6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(P6Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(lblP6))))
                .addGap(55, 55, 55))
        );

        panPerfiles.add(P6, "card4");

        P7.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_7.setBorder(null);

        lblP1_7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_7.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_7.setText("Perfil 1");

        btnP2_5.setBorder(null);

        lblP2_5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_5.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_5.setText("Perfil 2");

        btnP3_4.setBorder(null);

        lblP3_4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_4.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_4.setText("Perfil 3");

        btnP4_3.setBorder(null);

        lblP4_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP4_3.setText("Perfil 4");

        btnP5_2.setBorder(null);

        lblP5_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP5_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP5_2.setText("Perfil 5");

        btnP6_1.setBorder(null);

        lblP6_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP6_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP6_1.setText("Perfil 6");

        btnP7.setBorder(null);

        lblP7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP7.setForeground(new java.awt.Color(249, 249, 249));
        lblP7.setText("Perfil 7");

        javax.swing.GroupLayout P7Layout = new javax.swing.GroupLayout(P7);
        P7.setLayout(P7Layout);
        P7Layout.setHorizontalGroup(
            P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P7Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                        .addComponent(lblP1_7)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                        .addComponent(btnP1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addComponent(lblP2_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addComponent(lblP3_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP4_3)))
                .addGap(81, 81, 81)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP5_2)))
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                        .addComponent(btnP6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                        .addComponent(lblP6_1)
                        .addGap(121, 121, 121)))
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblP7)))
                .addGap(569, 569, 569))
        );
        P7Layout.setVerticalGroup(
            P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P7Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_5)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_7))))
                    .addGroup(P7Layout.createSequentialGroup()
                        .addComponent(btnP3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblP3_4))
                    .addComponent(btnP4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP4_3)
                            .addComponent(lblP5_2))))
                .addGap(56, 56, 56)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP7)
                            .addComponent(lblP6_1))))
                .addGap(55, 55, 55))
        );

        panPerfiles.add(P7, "card4");

        getContentPane().add(panPerfiles, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmElegirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmElegirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmElegirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmElegirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmElegirPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel P1;
    public javax.swing.JPanel P2;
    public javax.swing.JPanel P3;
    public javax.swing.JPanel P4;
    public javax.swing.JPanel P5;
    public javax.swing.JPanel P6;
    public javax.swing.JPanel P7;
    public javax.swing.JButton btnCrearPerfil;
    public javax.swing.JButton btnCrearPerfil1;
    public javax.swing.JButton btnCrearPerfil2;
    public javax.swing.JButton btnCrearPerfil3;
    public javax.swing.JButton btnCrearPerfil4;
    public javax.swing.JButton btnCrearPerfil5;
    public javax.swing.JButton btnEditarPerfiles;
    public javax.swing.JButton btnP1;
    public javax.swing.JButton btnP1_2;
    public javax.swing.JButton btnP1_3;
    public javax.swing.JButton btnP1_4;
    public javax.swing.JButton btnP1_5;
    public javax.swing.JButton btnP1_6;
    public javax.swing.JButton btnP1_7;
    public javax.swing.JButton btnP2;
    public javax.swing.JButton btnP2_1;
    public javax.swing.JButton btnP2_2;
    public javax.swing.JButton btnP2_3;
    public javax.swing.JButton btnP2_4;
    public javax.swing.JButton btnP2_5;
    public javax.swing.JButton btnP3;
    public javax.swing.JButton btnP3_1;
    public javax.swing.JButton btnP3_2;
    public javax.swing.JButton btnP3_3;
    public javax.swing.JButton btnP3_4;
    public javax.swing.JButton btnP4;
    public javax.swing.JButton btnP4_1;
    public javax.swing.JButton btnP4_2;
    public javax.swing.JButton btnP4_3;
    public javax.swing.JButton btnP5;
    public javax.swing.JButton btnP5_1;
    public javax.swing.JButton btnP5_2;
    public javax.swing.JButton btnP6;
    public javax.swing.JButton btnP6_1;
    public javax.swing.JButton btnP7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAvatar;
    public javax.swing.JLabel lblP1;
    public javax.swing.JLabel lblP1_2;
    public javax.swing.JLabel lblP1_3;
    public javax.swing.JLabel lblP1_4;
    public javax.swing.JLabel lblP1_5;
    public javax.swing.JLabel lblP1_6;
    public javax.swing.JLabel lblP1_7;
    public javax.swing.JLabel lblP2;
    public javax.swing.JLabel lblP2_1;
    public javax.swing.JLabel lblP2_2;
    public javax.swing.JLabel lblP2_3;
    public javax.swing.JLabel lblP2_4;
    public javax.swing.JLabel lblP2_5;
    public javax.swing.JLabel lblP3;
    public javax.swing.JLabel lblP3_1;
    public javax.swing.JLabel lblP3_2;
    public javax.swing.JLabel lblP3_3;
    public javax.swing.JLabel lblP3_4;
    public javax.swing.JLabel lblP4;
    public javax.swing.JLabel lblP4_1;
    public javax.swing.JLabel lblP4_2;
    public javax.swing.JLabel lblP4_3;
    public javax.swing.JLabel lblP5;
    public javax.swing.JLabel lblP5_1;
    public javax.swing.JLabel lblP5_2;
    public javax.swing.JLabel lblP6;
    public javax.swing.JLabel lblP6_1;
    public javax.swing.JLabel lblP7;
    public javax.swing.JPanel panPerfiles;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
