/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alexa
 */
public class frmEditarPerfiles extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmEditarPerfiles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnListo = new javax.swing.JButton();
        JLabel2 = new javax.swing.JLabel();
        panPerfiles = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        lblP1 = new javax.swing.JLabel();
        btnP1 = new javax.swing.JButton();
        P2 = new javax.swing.JPanel();
        btnP1_2 = new javax.swing.JButton();
        lblP1_2 = new javax.swing.JLabel();
        btnP2 = new javax.swing.JButton();
        lblP2 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        btnP1_3 = new javax.swing.JButton();
        lblP1_3 = new javax.swing.JLabel();
        btnP2_1 = new javax.swing.JButton();
        lblP2_1 = new javax.swing.JLabel();
        btnP3 = new javax.swing.JButton();
        lblP3 = new javax.swing.JLabel();
        P4 = new javax.swing.JPanel();
        btnP1_4 = new javax.swing.JButton();
        lblP1_4 = new javax.swing.JLabel();
        btnP2_2 = new javax.swing.JButton();
        lblP2_2 = new javax.swing.JLabel();
        btnP3_1 = new javax.swing.JButton();
        lblP3_1 = new javax.swing.JLabel();
        btnP4 = new javax.swing.JButton();
        lblP4 = new javax.swing.JLabel();
        P5 = new javax.swing.JPanel();
        btnP1_5 = new javax.swing.JButton();
        lblP1_5 = new javax.swing.JLabel();
        btnP2_3 = new javax.swing.JButton();
        lblP2_3 = new javax.swing.JLabel();
        btnP3_2 = new javax.swing.JButton();
        lblP3_2 = new javax.swing.JLabel();
        btnP4_1 = new javax.swing.JButton();
        lblP4_1 = new javax.swing.JLabel();
        btnP5 = new javax.swing.JButton();
        lblP5 = new javax.swing.JLabel();
        P6 = new javax.swing.JPanel();
        btnP1_6 = new javax.swing.JButton();
        lblP1_6 = new javax.swing.JLabel();
        btnP2_4 = new javax.swing.JButton();
        lblP2_4 = new javax.swing.JLabel();
        btnP3_3 = new javax.swing.JButton();
        lblP3_3 = new javax.swing.JLabel();
        btnP4_2 = new javax.swing.JButton();
        lblP4_2 = new javax.swing.JLabel();
        btnP5_1 = new javax.swing.JButton();
        lblP5_1 = new javax.swing.JLabel();
        btnP6 = new javax.swing.JButton();
        lblP6 = new javax.swing.JLabel();
        P7 = new javax.swing.JPanel();
        btnP1_7 = new javax.swing.JButton();
        lblP1_7 = new javax.swing.JLabel();
        btnP2_5 = new javax.swing.JButton();
        lblP2_5 = new javax.swing.JLabel();
        btnP3_4 = new javax.swing.JButton();
        lblP3_4 = new javax.swing.JLabel();
        btnP4_3 = new javax.swing.JButton();
        lblP4_3 = new javax.swing.JLabel();
        btnP5_2 = new javax.swing.JButton();
        lblP5_2 = new javax.swing.JLabel();
        btnP6_1 = new javax.swing.JButton();
        lblP6_1 = new javax.swing.JLabel();
        btnP7 = new javax.swing.JButton();
        lblP7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panPrincipal.setBackground(new java.awt.Color(26, 29, 41));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1280, 205));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1280, 205));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1280, 205));
        panPrincipal.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 249, 249));
        jLabel1.setText("Editar Perfiles");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/80px-Disney_logo.png"))); // NOI18N

        btnListo.setBackground(new java.awt.Color(0, 114, 210));
        btnListo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnListo.setForeground(new java.awt.Color(249, 249, 249));
        btnListo.setText("LISTO");
        btnListo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        JLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(204, 204, 204));
        JLabel2.setText("Seleccion un perfil para editar.");

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap(812, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(JLabel2))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panPrincipal, java.awt.BorderLayout.PAGE_START);

        panPerfiles.setBackground(new java.awt.Color(255, 255, 255));
        panPerfiles.setForeground(new java.awt.Color(255, 255, 255));
        panPerfiles.setLayout(new java.awt.CardLayout());

        P1.setBackground(new java.awt.Color(26, 29, 41));

        lblP1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1.setForeground(new java.awt.Color(249, 249, 249));
        lblP1.setText("Perfil 1");

        btnP1.setBorder(null);

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(567, 567, 567)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                        .addComponent(lblP1)
                        .addGap(23, 23, 23))
                    .addComponent(btnP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(606, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnP1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblP1)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        panPerfiles.add(P1, "card3");

        P2.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_2.setBorder(null);

        lblP1_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_2.setText("Perfil 1");

        btnP2.setBorder(null);

        lblP2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2.setForeground(new java.awt.Color(249, 249, 249));
        lblP2.setText("Perfil 2");

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(btnP1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(lblP1_2)
                        .addGap(140, 140, 140)
                        .addComponent(lblP2)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP2)
                    .addComponent(lblP1_2))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        panPerfiles.add(P2, "card2");

        P3.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_3.setBorder(null);

        lblP1_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_3.setText("Perfil 1");

        btnP2_1.setBorder(null);

        lblP2_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_1.setText("Perfil 2");

        btnP3.setBorder(null);

        lblP3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3.setForeground(new java.awt.Color(249, 249, 249));
        lblP3.setText("Perfil 3");

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(lblP1_3)
                        .addGap(146, 146, 146)
                        .addComponent(lblP2_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(btnP1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnP2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(lblP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblP3))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_1)
                            .addGroup(P3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_3)))))
                .addGap(195, 195, 195))
        );

        panPerfiles.add(P3, "card4");

        P4.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_4.setBorder(null);

        lblP1_4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_4.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_4.setText("Perfil 1");

        btnP2_2.setBorder(null);

        lblP2_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_2.setText("Perfil 2");

        btnP3_1.setBorder(null);

        lblP3_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_1.setText("Perfil 3");

        btnP4.setBorder(null);
        btnP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP4ActionPerformed(evt);
            }
        });

        lblP4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4.setForeground(new java.awt.Color(249, 249, 249));
        lblP4.setText("Perfil 4");

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(lblP1_4)
                        .addGap(146, 146, 146)
                        .addComponent(lblP2_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(btnP1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnP2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addComponent(lblP3_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnP4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblP4)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP3_1)
                            .addComponent(lblP4)))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_2)
                            .addGroup(P4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_4)))))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        panPerfiles.add(P4, "card4");

        P5.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_5.setBorder(null);

        lblP1_5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_5.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_5.setText("Perfil 1");

        btnP2_3.setBorder(null);

        lblP2_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_3.setText("Perfil 2");

        btnP3_2.setBorder(null);

        lblP3_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_2.setText("Perfil 3");

        btnP4_1.setBorder(null);

        lblP4_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP4_1.setText("Perfil 4");

        btnP5.setBorder(null);

        lblP5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP5.setForeground(new java.awt.Color(249, 249, 249));
        lblP5.setText("Perfil 5");

        javax.swing.GroupLayout P5Layout = new javax.swing.GroupLayout(P5);
        P5.setLayout(P5Layout);
        P5Layout.setHorizontalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P5Layout.createSequentialGroup()
                        .addComponent(lblP1_5)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P5Layout.createSequentialGroup()
                        .addComponent(btnP1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addComponent(lblP2_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addComponent(lblP3_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnP3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP4_1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP5)))
                .addGap(242, 242, 242))
        );
        P5Layout.setVerticalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_3)
                            .addGroup(P5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_5))))
                    .addGroup(P5Layout.createSequentialGroup()
                        .addComponent(btnP3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblP3_2))
                    .addComponent(btnP4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP4_1)
                            .addComponent(lblP5))))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        panPerfiles.add(P5, "card4");

        P6.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_6.setBorder(null);

        lblP1_6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_6.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_6.setText("Perfil 1");

        btnP2_4.setBorder(null);

        lblP2_4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_4.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_4.setText("Perfil 2");

        btnP3_3.setBorder(null);

        lblP3_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_3.setText("Perfil 3");

        btnP4_2.setBorder(null);

        lblP4_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP4_2.setText("Perfil 4");

        btnP5_1.setBorder(null);

        lblP5_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP5_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP5_1.setText("Perfil 5");

        btnP6.setBorder(null);

        lblP6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP6.setForeground(new java.awt.Color(249, 249, 249));
        lblP6.setText("Perfil 6");

        javax.swing.GroupLayout P6Layout = new javax.swing.GroupLayout(P6);
        P6.setLayout(P6Layout);
        P6Layout.setHorizontalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnP6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(P6Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblP6)))
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                                .addComponent(lblP1_6)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                                .addComponent(btnP1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(P6Layout.createSequentialGroup()
                                .addComponent(lblP2_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnP2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(P6Layout.createSequentialGroup()
                                .addComponent(lblP3_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnP3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(81, 81, 81)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP4_2)))
                .addGap(81, 81, 81)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblP5_1)))
                .addGap(204, 204, 204))
        );
        P6Layout.setVerticalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P6Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_4)
                            .addGroup(P6Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_6))))
                    .addGroup(P6Layout.createSequentialGroup()
                        .addComponent(btnP3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblP3_3))
                    .addComponent(btnP4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP4_2)
                            .addComponent(lblP5_1))))
                .addGap(34, 34, 34)
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblP6)))
                .addGap(72, 72, 72))
        );

        panPerfiles.add(P6, "card4");

        P7.setBackground(new java.awt.Color(26, 29, 41));

        btnP1_7.setBorder(null);

        lblP1_7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP1_7.setForeground(new java.awt.Color(249, 249, 249));
        lblP1_7.setText("Perfil 1");

        btnP2_5.setBorder(null);

        lblP2_5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP2_5.setForeground(new java.awt.Color(249, 249, 249));
        lblP2_5.setText("Perfil 2");

        btnP3_4.setBorder(null);

        lblP3_4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP3_4.setForeground(new java.awt.Color(249, 249, 249));
        lblP3_4.setText("Perfil 3");

        btnP4_3.setBorder(null);

        lblP4_3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP4_3.setForeground(new java.awt.Color(249, 249, 249));
        lblP4_3.setText("Perfil 4");

        btnP5_2.setBorder(null);

        lblP5_2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP5_2.setForeground(new java.awt.Color(249, 249, 249));
        lblP5_2.setText("Perfil 5");

        btnP6_1.setBorder(null);

        lblP6_1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP6_1.setForeground(new java.awt.Color(249, 249, 249));
        lblP6_1.setText("Perfil 6");

        btnP7.setBorder(null);

        lblP7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblP7.setForeground(new java.awt.Color(249, 249, 249));
        lblP7.setText("Perfil 7");

        javax.swing.GroupLayout P7Layout = new javax.swing.GroupLayout(P7);
        P7.setLayout(P7Layout);
        P7Layout.setHorizontalGroup(
            P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P7Layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                                .addComponent(lblP1_7)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                                .addComponent(btnP1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addComponent(lblP2_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnP2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addComponent(lblP3_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnP3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblP4_3)))
                        .addGap(81, 81, 81)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblP5_2)))
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                                .addComponent(btnP6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                                .addComponent(lblP6_1)
                                .addGap(121, 121, 121)))
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblP7)))
                        .addGap(472, 472, 472))))
        );
        P7Layout.setVerticalGroup(
            P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P7Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnP2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP2_5)
                            .addGroup(P7Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblP1_7))))
                    .addGroup(P7Layout.createSequentialGroup()
                        .addComponent(btnP3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblP3_4))
                    .addComponent(btnP4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblP4_3)
                            .addComponent(lblP5_2))))
                .addGap(40, 40, 40)
                .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnP6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP7)
                            .addComponent(lblP6_1))))
                .addGap(55, 55, 55))
        );

        panPerfiles.add(P7, "card4");

        getContentPane().add(panPerfiles, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnP4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditarPerfiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel2;
    public javax.swing.JPanel P1;
    public javax.swing.JPanel P2;
    public javax.swing.JPanel P3;
    public javax.swing.JPanel P4;
    public javax.swing.JPanel P5;
    public javax.swing.JPanel P6;
    public javax.swing.JPanel P7;
    public javax.swing.JButton btnListo;
    public javax.swing.JButton btnP1;
    public javax.swing.JButton btnP1_2;
    public javax.swing.JButton btnP1_3;
    public javax.swing.JButton btnP1_4;
    public javax.swing.JButton btnP1_5;
    public javax.swing.JButton btnP1_6;
    public javax.swing.JButton btnP1_7;
    public javax.swing.JButton btnP2;
    public javax.swing.JButton btnP2_1;
    public javax.swing.JButton btnP2_2;
    public javax.swing.JButton btnP2_3;
    public javax.swing.JButton btnP2_4;
    public javax.swing.JButton btnP2_5;
    public javax.swing.JButton btnP3;
    public javax.swing.JButton btnP3_1;
    public javax.swing.JButton btnP3_2;
    public javax.swing.JButton btnP3_3;
    public javax.swing.JButton btnP3_4;
    public javax.swing.JButton btnP4;
    public javax.swing.JButton btnP4_1;
    public javax.swing.JButton btnP4_2;
    public javax.swing.JButton btnP4_3;
    public javax.swing.JButton btnP5;
    public javax.swing.JButton btnP5_1;
    public javax.swing.JButton btnP5_2;
    public javax.swing.JButton btnP6;
    public javax.swing.JButton btnP6_1;
    public javax.swing.JButton btnP7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAvatar;
    public javax.swing.JLabel lblP1;
    public javax.swing.JLabel lblP1_2;
    public javax.swing.JLabel lblP1_3;
    public javax.swing.JLabel lblP1_4;
    public javax.swing.JLabel lblP1_5;
    public javax.swing.JLabel lblP1_6;
    public javax.swing.JLabel lblP1_7;
    public javax.swing.JLabel lblP2;
    public javax.swing.JLabel lblP2_1;
    public javax.swing.JLabel lblP2_2;
    public javax.swing.JLabel lblP2_3;
    public javax.swing.JLabel lblP2_4;
    public javax.swing.JLabel lblP2_5;
    public javax.swing.JLabel lblP3;
    public javax.swing.JLabel lblP3_1;
    public javax.swing.JLabel lblP3_2;
    public javax.swing.JLabel lblP3_3;
    public javax.swing.JLabel lblP3_4;
    public javax.swing.JLabel lblP4;
    public javax.swing.JLabel lblP4_1;
    public javax.swing.JLabel lblP4_2;
    public javax.swing.JLabel lblP4_3;
    public javax.swing.JLabel lblP5;
    public javax.swing.JLabel lblP5_1;
    public javax.swing.JLabel lblP5_2;
    public javax.swing.JLabel lblP6;
    public javax.swing.JLabel lblP6_1;
    public javax.swing.JLabel lblP7;
    public javax.swing.JPanel panPerfiles;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
