/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alexa
 */
public class frmElegirAvatar extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmElegirAvatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSuscribirse1 = new javax.swing.JLabel();
        btnSuscribirse2 = new javax.swing.JLabel();
        btnSaltar = new javax.swing.JButton();
        btnM1 = new javax.swing.JButton();
        btnM2 = new javax.swing.JButton();
        btnM4 = new javax.swing.JButton();
        btnM3 = new javax.swing.JButton();
        btnM6 = new javax.swing.JButton();
        btnM5 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnSuscribirse3 = new javax.swing.JLabel();
        btnN2 = new javax.swing.JButton();
        btnN1 = new javax.swing.JButton();
        btnN4 = new javax.swing.JButton();
        btnN3 = new javax.swing.JButton();
        btnN5 = new javax.swing.JButton();
        btnN6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 720));

        panPrincipal.setBackground(new java.awt.Color(26, 29, 41));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1280, 720));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1280, 720));
        panPrincipal.setPreferredSize(new java.awt.Dimension(1280, 1000));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 249, 249));
        jLabel1.setText("Elegir avatar");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/80px-Disney_logo.png"))); // NOI18N

        btnSuscribirse1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSuscribirse1.setForeground(new java.awt.Color(249, 249, 249));
        btnSuscribirse1.setText("Mickey Mouse y compañia");

        btnSuscribirse2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSuscribirse2.setForeground(new java.awt.Color(249, 249, 249));
        btnSuscribirse2.setText("Disney");

        btnSaltar.setBackground(new java.awt.Color(153, 153, 153));
        btnSaltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSaltar.setForeground(new java.awt.Color(249, 249, 249));
        btnSaltar.setText("SALTAR");
        btnSaltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/micky/micky_1.JPG"))); // NOI18N
        btnM1.setBorderPainted(false);
        btnM1.setContentAreaFilled(false);

        btnM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/micky/micky_2.JPG"))); // NOI18N
        btnM2.setBorderPainted(false);
        btnM2.setContentAreaFilled(false);

        btnM4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/micky/micky_4.JPG"))); // NOI18N
        btnM4.setBorderPainted(false);
        btnM4.setContentAreaFilled(false);

        btnM3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/micky/micky_3.JPG"))); // NOI18N
        btnM3.setBorderPainted(false);
        btnM3.setContentAreaFilled(false);

        btnM6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/micky/micky_6.JPG"))); // NOI18N
        btnM6.setBorderPainted(false);
        btnM6.setContentAreaFilled(false);

        btnM5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/micky/micky_5.JPG"))); // NOI18N
        btnM5.setBorderPainted(false);
        btnM5.setContentAreaFilled(false);

        btnD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/disney/infantil_1.JPG"))); // NOI18N
        btnD1.setBorderPainted(false);
        btnD1.setContentAreaFilled(false);
        btnD1.setFocusPainted(false);

        btnD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/disney/infantil_2.JPG"))); // NOI18N
        btnD2.setBorderPainted(false);
        btnD2.setContentAreaFilled(false);

        btnD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/disney/infantil_3.JPG"))); // NOI18N
        btnD3.setBorderPainted(false);
        btnD3.setContentAreaFilled(false);

        btnD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/disney/infantil_4.JPG"))); // NOI18N
        btnD4.setBorderPainted(false);
        btnD4.setContentAreaFilled(false);

        btnD6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/disney/infantil_6.JPG"))); // NOI18N
        btnD6.setBorderPainted(false);
        btnD6.setContentAreaFilled(false);

        btnD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/disney/infantil_5.JPG"))); // NOI18N
        btnD5.setBorderPainted(false);
        btnD5.setContentAreaFilled(false);

        btnSuscribirse3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSuscribirse3.setForeground(new java.awt.Color(249, 249, 249));
        btnSuscribirse3.setText("National Geographic");

        btnN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/National/national_2.JPG"))); // NOI18N
        btnN2.setBorderPainted(false);
        btnN2.setContentAreaFilled(false);

        btnN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/National/national_1.JPG"))); // NOI18N
        btnN1.setBorderPainted(false);
        btnN1.setContentAreaFilled(false);
        btnN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnN1ActionPerformed(evt);
            }
        });

        btnN4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/National/national_4.JPG"))); // NOI18N
        btnN4.setBorderPainted(false);
        btnN4.setContentAreaFilled(false);

        btnN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/National/national_3.JPG"))); // NOI18N
        btnN3.setBorderPainted(false);
        btnN3.setContentAreaFilled(false);

        btnN5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/National/national_5.JPG"))); // NOI18N
        btnN5.setBorderPainted(false);
        btnN5.setContentAreaFilled(false);

        btnN6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Avatar/National/national_6.JPG"))); // NOI18N
        btnN6.setBorderPainted(false);
        btnN6.setContentAreaFilled(false);

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(btnSuscribirse3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPrincipalLayout.createSequentialGroup()
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSuscribirse1)
                                    .addComponent(jLabel1)
                                    .addComponent(btnSuscribirse2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPrincipalLayout.createSequentialGroup()
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)
                                        .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)
                                        .addComponent(btnD2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnN1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnN2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnD3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(130, 130, 130)
                                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnD4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnM4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnN3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(btnN4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(btnD6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnN5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(btnN6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(37, 37, 37))))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaltar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(btnSuscribirse2)
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnSuscribirse1)
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnSuscribirse3)
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnN2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panPrincipal);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmElegirAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmElegirAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmElegirAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmElegirAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmElegirAvatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnD1;
    public javax.swing.JButton btnD2;
    public javax.swing.JButton btnD3;
    public javax.swing.JButton btnD4;
    public javax.swing.JButton btnD5;
    public javax.swing.JButton btnD6;
    public javax.swing.JButton btnM1;
    public javax.swing.JButton btnM2;
    public javax.swing.JButton btnM3;
    public javax.swing.JButton btnM4;
    public javax.swing.JButton btnM5;
    public javax.swing.JButton btnM6;
    public javax.swing.JButton btnN1;
    public javax.swing.JButton btnN2;
    public javax.swing.JButton btnN3;
    public javax.swing.JButton btnN4;
    public javax.swing.JButton btnN5;
    public javax.swing.JButton btnN6;
    public javax.swing.JButton btnSaltar;
    private javax.swing.JLabel btnSuscribirse1;
    private javax.swing.JLabel btnSuscribirse2;
    private javax.swing.JLabel btnSuscribirse3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
