/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alexa
 */
public class frmSuscribirse4 extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmSuscribirse4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gplan = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        rbtnMensual = new javax.swing.JRadioButton();
        rbtnAnual = new javax.swing.JRadioButton();
        btnTarjeta = new javax.swing.JButton();
        btnPaypal = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panPago = new javax.swing.JPanel();
        panTarjeta = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        txtNumTarjeta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomTarjeta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFven = new javax.swing.JTextField();
        panPaypal = new javax.swing.JPanel();
        btnPagarPaypal = new javax.swing.JButton();
        txtPaypal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jScrollPane1.setToolTipText("");
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);

        panPrincipal.setBackground(new java.awt.Color(26, 29, 41));
        panPrincipal.setMaximumSize(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 249, 249));
        jLabel1.setText("Inicia tu prueba sin costo de");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/200px-Disney_logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(172, 172, 174));
        jLabel4.setText("PASO 4 DE 4");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Luego,");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 249, 249));
        jLabel7.setText("7 dias");

        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("PRECIO");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("cancela en cualquier momento.");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cancelala antes del");

        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("FECHA");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("para evitar cargos.");

        lblAlerta.setForeground(new java.awt.Color(255, 0, 0));

        rbtnMensual.setBackground(new java.awt.Color(153, 153, 153));
        Gplan.add(rbtnMensual);
        rbtnMensual.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMensual.setSelected(true);
        rbtnMensual.setText("Mensual PEN 25.90");
        rbtnMensual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbtnMensual.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        rbtnAnual.setBackground(new java.awt.Color(153, 153, 153));
        Gplan.add(rbtnAnual);
        rbtnAnual.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAnual.setText("Anual PEN 259.9.");

        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta.png"))); // NOI18N
        btnTarjeta.setBorderPainted(false);
        btnTarjeta.setContentAreaFilled(false);
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });

        btnPaypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paypal.png"))); // NOI18N
        btnPaypal.setBorder(null);

        btnCancelar.setBackground(new java.awt.Color(0, 114, 210));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(249, 249, 249));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panPago.setLayout(new java.awt.CardLayout());

        panTarjeta.setBackground(new java.awt.Color(26, 29, 41));

        btnContinuar.setBackground(new java.awt.Color(0, 114, 210));
        btnContinuar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(249, 249, 249));
        btnContinuar.setText("ACEPTAR Y SUSCRIBIRSE");
        btnContinuar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        txtNumTarjeta.setBackground(new java.awt.Color(49, 52, 62));
        txtNumTarjeta.setForeground(new java.awt.Color(249, 249, 249));
        txtNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTarjetaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(172, 172, 174));
        jLabel9.setText("NOMBRE DE LA TARJETA");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(172, 172, 174));
        jLabel10.setText("NUMERO DE LA TARJETA");

        txtNomTarjeta.setBackground(new java.awt.Color(49, 52, 62));
        txtNomTarjeta.setForeground(new java.awt.Color(249, 249, 249));
        txtNomTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomTarjetaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(172, 172, 174));
        jLabel11.setText("FECHA DE VENCIMIENTO");

        txtCVV.setBackground(new java.awt.Color(49, 52, 62));
        txtCVV.setForeground(new java.awt.Color(249, 249, 249));
        txtCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCVVActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(172, 172, 174));
        jLabel12.setText("CODIGO DE SEGURIDAD");

        txtFven.setBackground(new java.awt.Color(49, 52, 62));
        txtFven.setForeground(new java.awt.Color(249, 249, 249));
        txtFven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFvenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTarjetaLayout = new javax.swing.GroupLayout(panTarjeta);
        panTarjeta.setLayout(panTarjetaLayout);
        panTarjetaLayout.setHorizontalGroup(
            panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTarjetaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTarjetaLayout.createSequentialGroup()
                        .addGroup(panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panTarjetaLayout.createSequentialGroup()
                        .addGroup(panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNomTarjeta)
                    .addComponent(txtNumTarjeta)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        panTarjetaLayout.setVerticalGroup(
            panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTarjetaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFven, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panPago.add(panTarjeta, "card3");

        panPaypal.setBackground(new java.awt.Color(26, 29, 41));

        btnPagarPaypal.setBackground(new java.awt.Color(0, 114, 210));
        btnPagarPaypal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPagarPaypal.setForeground(new java.awt.Color(249, 249, 249));
        btnPagarPaypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icoPaypal.png"))); // NOI18N
        btnPagarPaypal.setText("Pagar con");
        btnPagarPaypal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPagarPaypal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtPaypal.setBackground(new java.awt.Color(49, 52, 62));
        txtPaypal.setForeground(new java.awt.Color(249, 249, 249));
        txtPaypal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaypalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(172, 172, 174));
        jLabel13.setText("INGRESE SU CUENTA DE PAYPAL");

        javax.swing.GroupLayout panPaypalLayout = new javax.swing.GroupLayout(panPaypal);
        panPaypal.setLayout(panPaypalLayout);
        panPaypalLayout.setHorizontalGroup(
            panPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPaypalLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(panPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(panPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPaypal)
                        .addComponent(btnPagarPaypal, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        panPaypalLayout.setVerticalGroup(
            panPaypalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPaypalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPaypal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnPagarPaypal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        panPago.add(panPaypal, "card2");

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(panPago, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 444, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnMensual)
                                    .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(rbtnAnual))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(btnPaypal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPrecio)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblFecha)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMensual)
                    .addComponent(rbtnAnual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPaypal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panPago, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(panPrincipal);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTarjetaActionPerformed

    private void txtNomTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomTarjetaActionPerformed

    private void txtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCVVActionPerformed

    private void txtFvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFvenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFvenActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarjetaActionPerformed

    private void txtPaypalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaypalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaypalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuscribirse4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gplan;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnContinuar;
    public javax.swing.JButton btnPagarPaypal;
    public javax.swing.JButton btnPaypal;
    public javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblAlerta;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblPrecio;
    public javax.swing.JPanel panPago;
    public javax.swing.JPanel panPaypal;
    private javax.swing.JPanel panPrincipal;
    public javax.swing.JPanel panTarjeta;
    public javax.swing.JRadioButton rbtnAnual;
    public javax.swing.JRadioButton rbtnMensual;
    public javax.swing.JTextField txtCVV;
    public javax.swing.JTextField txtFven;
    public javax.swing.JTextField txtNomTarjeta;
    public javax.swing.JTextField txtNumTarjeta;
    public javax.swing.JTextField txtPaypal;
    // End of variables declaration//GEN-END:variables
}
