/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alexa
 */
public class frmSuscribirse2 extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmSuscribirse2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAceptarCont = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panAcuerdo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panPrincipal.setBackground(new java.awt.Color(26, 29, 41));
        panPrincipal.setMaximumSize(new java.awt.Dimension(1280, 720));
        panPrincipal.setMinimumSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 249, 249));
        jLabel1.setText("Acuerdo de suscripción");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/200px-Disney_logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(172, 172, 174));
        jLabel4.setText("PASO 2 DE 4");

        btnAceptarCont.setBackground(new java.awt.Color(0, 114, 210));
        btnAceptarCont.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAceptarCont.setForeground(new java.awt.Color(249, 249, 249));
        btnAceptarCont.setText("ACEPTAR Y CONTINUAR");
        btnAceptarCont.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 249, 249));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Al hacer clic en Aceptar y continuar, confirmas que has leído y aceptas el Acuerdo de "
            + "suscripción en su totalidad.<html>");

        jScrollPane1.setBackground(new java.awt.Color(26, 29, 41));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panAcuerdo.setBackground(new java.awt.Color(26, 29, 41));

        jLabel5.setForeground(new java.awt.Color(249, 249, 249));
        jLabel5.setText("<html>Acuerdo de Suscripción a Disney+ (Perú)"
            + "Actualización: 3 de noviembre de 2020."
            + "Disney DTC LATAM, Inc. (\"Disney+\", \"nosotros\", \"nos\", \"nuestro\") con domicilio en"
            + "2400 West Alameda Avenue, Burbank, California 91521, United States of"
            + "America y número de identificación fiscal 75-3016153 te da la bienvenida al"
            + "Servicio Disney+. El \"Servicio Disney+\" es un servicio por suscripción"
            + "personalizado, que incluye el sitio web del Servicio Disney+, su aplicación y los"
            + "contenidos y servicios asociados."
            + "EL PRESENTE ACUERDO DE SUSCRIPCIÓN (\"ACUERDO DE SUSCRIPCIÓN A"
            + "DISNEY+\" O \" ACUERDO\") RIGE EL USO QUE HAGA DEL SERVICIO DISNEY+."
            + "LEE CON ATENCIÓN EL ACUERDO ANTES DE HACER USO DEL SERVICIO DISNEY+."
            + "Al hacer clic en \"Aceptar y continuar\" u otro mecanismo habitual para este tipo de"
            + "servicios durante el proceso de registro de Disney, aceptas de forma plena y sin"
            + "reservas el presente Acuerdo de Suscripción de Disney+ y ratificas tu acuerdo al"
            + "utilizar cualquier elemento del Servicio Disney+. Si no aceptas el presente Acuerdo"
            + "de Suscripción de Disney+, no puedes usar el Servicio Disney+."
            + "Nos reservamos el derecho a modificar este Acuerdo en cualquier momento según"
            + "lo estimemos necesario. Cualquier modificación que afecte materialmente tus"
            + "derechos u obligaciones entrará en vigor a los treinta (30) días del envío de la"
            + "correspondiente notificación a la dirección de correo electrónico registrado con tu"
            + "membresía. Si no estuvieras de acuerdo con cualquier modificación a este Acuerdo"
            + "en la forma indicada, podrás cancelar tu suscripción al Servicio Disney+ conforme"
            + "a los términos y condiciones que se indican en el apartado 2 debajo. Además,"
            + " ciertos elementos del Servicio Disney+ pueden variar en cualquier momento sin"
            + "necesidad de notificación, por ejemplo por razones relativas a evoluciones"
            + "técnicas, siempre y cuando no impliquen un incremento del precio ni una"
            + "alteración de la calidad o modificación significativa de las funcionalidades del"
            + "Servicio Disney+.<html>"
        );

        javax.swing.GroupLayout panAcuerdoLayout = new javax.swing.GroupLayout(panAcuerdo);
        panAcuerdo.setLayout(panAcuerdoLayout);
        panAcuerdoLayout.setHorizontalGroup(
            panAcuerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAcuerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panAcuerdoLayout.setVerticalGroup(
            panAcuerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAcuerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(panAcuerdo);

        btnCancelar.setBackground(new java.awt.Color(0, 114, 210));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(249, 249, 249));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(513, 513, 513)
                                .addComponent(jLabel2))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(432, 432, 432)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(btnAceptarCont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 455, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptarCont, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        getContentPane().add(panPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSuscribirse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuscribirse2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarCont;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panAcuerdo;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
